import { NativeCode } from 'uts.sdk.modules.srFileChoose';

export type ChooseFileResult = {
    size: number;
    path: string;
    name: string;
}

export type ChooseFileOptions = {
    complete?: (res: ChooseFileResult | any) => void;
    success?: (res: ChooseFileResult) => void;
    fail?: (err: any) => void;
}

export function chooseFileFromModule(options: ChooseFileOptions) {
    NativeCode.openFilePicker((path: string | null, size: number, name: string) => {
        if (path != null) {
            const resData: ChooseFileResult = {
                size: size,
                path: path,
                name: name
            };
            if (options.success != null) options.success!(resData);
            if (options.complete != null) options.complete!(resData);
        } else {
            const err = { errMsg: "cancel or get path failed" };
            if (options.fail != null) options.fail!(err);
            if (options.complete != null) options.complete!(err);
        }
    });
}
